### ISSUE TITLE
Inconsistent tests

### ISSUE THREAD

**Issue by mccalluc** [refinery-platform/django_docker_engine#146]
Multiple times I've see individual tests fail on Travis, been unable to reproduce them, and when I re-ran on Travis they were gone. I want keep a list of them here, and if particular ones are more frequent than others, I want to note that.

Working on 0.0.57, Django2 environment, Travis fails:
```
tests.test_live.PathRoutingMechanicalSoupTests.testDebuggerLaunch
tests.test_live.HostRoutingClientTests.test_please_wait
```

**Comment by mccalluc** [comment]
```
======================================================================
ERROR: test_please_wait (tests.test_live.HostRoutingClientTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/refinery-platform/django_docker_engine/django_docker_engine/container_managers/docker_engine.py", line 156, in get_url
    http_port_info = port_infos['{}/tcp'.format(container_port)]
KeyError: '80/tcp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/refinery-platform/django_docker_engine/tests/test_live.py", line 137, in test_please_wait
    labels={'subprocess-test-label': 'True'}
  File "/home/travis/build/refinery-platform/django_docker_engine/django_docker_engine/docker_utils.py", line 241, in run
    return self.lookup_container_url(container_spec.container_name)
  File "/home/travis/build/refinery-platform/django_docker_engine/django_docker_engine/docker_utils.py", line 83, in lookup_container_url
    return self._containers_manager.get_url(container_name)
  File "/home/travis/build/refinery-platform/django_docker_engine/django_docker_engine/container_managers/docker_engine.py", line 160, in get_url
    container_name, container_port, port_infos
django_docker_engine.container_managers.docker_engine.ExpectedPortMissing: On container container-name, port 80 is not available, but these are: {}

======================================================================
ERROR: testDebuggerLaunch (tests.test_live.PathRoutingMechanicalSoupTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/python/3.6.3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```
